stages:
  - code_quality

code_quality:
  stage: code_quality
  tags:
    - "shared-shell-2"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG || $CI_PIPELINE_SOURCE == 'merge_request_event'"
      when: always
    - if: "$CODE_QUALITY_DISABLED"
      when: never
  before_script:
  - pip3 install pep8
  - pip3 install pylint
  script:
    - git fetch --all
    - codeclimate analyze -f json $(git diff --name-only origin/$CI_DEFAULT_BRANCH) | jq 'del(.[] | select(.type == "measurement"))' > gl-code-quality-report.json
  artifacts:
    expire_in: 1 week
    paths:
      - gl-code-quality-report.json
    reports:
      codequality: gl-code-quality-report.json
